name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checko ut code
        uses: actions/checkout@v2

      - name: Set up environment variables
        run: echo "APIKEY=${{ secrets.APIKEY }}" >> $GITHUB_ENV
      
      
      # Add more steps for your build, test, and deployment process
